name: Release Psych Extended

on: workflow_dispatch

jobs:
  Build:
    name: ${{ matrix.name }}
    strategy:
      matrix:
        include:
          - name: Windows
            os: windows-2022
            buildArgs: windows
            setupCommand: .\"setup/windows.bat"
            artifactName: windowsBuild-x86_64
            artifactPath: export\release\windows\bin\*
            system: Windows
            release: Enabled
          - name: Android-Arm64
            os: ubuntu-24.04
            buildArgs: "android -ONLY_ARM64 -final"
            setupCommand: sh ./setup/mobile.sh
            artifactName: androidBuild-Arm64
            artifactPath: "export/release/android/bin/app/build/outputs/apk/release/*.apk"
            system: Android
            release: Enabled
          - name: Android-Armv7
            os: ubuntu-24.04
            buildArgs: "android -ONLY_ARMV7 -final"
            setupCommand: sh ./setup/mobile.sh
            artifactName: androidBuild-Armv7
            artifactPath: "export/release/android/bin/app/build/outputs/apk/release/*.apk"
            system: Android
            release: Enabled
    uses: ./.github/workflows/build.yml
    with:
        name: ${{ matrix.name }}
        os: ${{ matrix.os }}
        buildArgs: ${{ matrix.buildArgs }}
        setupCommand: ${{ matrix.setupCommand }}
        artifactName: ${{ matrix.artifactName }}
        artifactPath: ${{ matrix.artifactPath }}
        system: ${{ matrix.system }}
        
  Releaser:
    if: matrix.release == Enabled
    needs: [Android-Arm64, Android-Armv7, Windows]
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Download Android Build
        if: matrix.release == Enabled
        uses: actions/download-artifact@main
        with:
           name: androidBuild-VirtualPad
           path: /home/runner

      - name: Move Android File
        if: matrix.release == Enabled
        run: mv /home/runner/PsychExtended-release.apk /home/runner/PsychExtended-1.0.2-PreRelease.apk

      - name: Download Windows Build
        if: matrix.release == Enabled
        uses: actions/download-artifact@main
        with:
           name: windowsBuild
           path: /home/runner

      - name: Publish The Release
        if: matrix.release == Enabled
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: "1.0.2-prerelease"
          title: "1.0.2 PreRelease - Scriptable States Alpha"
          files: |
            /home/runner/*.apk
            /home/runner/*.zip
            /home/runner/*.tar